### ISSUE TITLE
Move Nightawks project to dsciitbbs

### ISSUE THREAD

**Issue by apsknight** [dsciitbbs/iitbbsguide#3]
[Nightawks](https://github.com/nightawks)

**Comment by PalAditya** [comment]
@apsknight Do you mean migrating all the repositories, or only the ones that would be useful in this case, like [`iitbhubaneswarnewsapi`](https://github.com/nightawks/iitbbsnewsapi) ?

**Comment by apsknight** [comment]
@PalAditya For now, let's go ahead with <https://github.com/nightawks/iitbbsnewsapi> only.

**Comment by apsknight** [comment]
@PalAditya Are you working on this?

**Comment by PalAditya** [comment]
Yes, let's just get it done. I am going to go ahead and fork it as of now, but please give your input on whether we should use the script of @MadhavChoudhary  for the purpose?

**Comment by apsknight** [comment]
@PalAditya Yes, go ahead. @MadhavChoudhary Can you please help us with this?

**Comment by madhavtummala** [comment]
Yes, I can.
The script uses `date` bash command. I have observed that it is not truly cross platform because of that. But it sure works in my machine as expected, so I can run it.
If we don't want to redistribute commit dates, then commenting out that part, will make it work on any computer. 
@apsknight Do you want me to run?

**Comment by madhavtummala** [comment]
Wait. What is the issue at all? 
I see the commits in [nightawks](https://github.com/nightawks/iitbbsnewsapi) repository are made by @PalAditya and @apsknight.
So just clone, set a new remote at `dsciitbbs` and push.
Even simple, repository can be migrated between organisations in repository settings.

**Comment by apsknight** [comment]
@PalAditya I see you have already made some commits. Since a fork already exists, I can't transfer the repo.

Also, @MadhavChoudhary Current Nightawks repo is CI/CD with Heroku deployment. Will it remain so after transferring to dsciitbbs?

**Comment by PalAditya** [comment]
Create a PR, merge it, delete the fork, transfer :)

**Comment by madhavtummala** [comment]
Looks like it is done. 👍

**Comment by apsknight** [comment]
Yes, closing this issue.
